In [1]:
import pandas as pd
import numpy as np

In [2]:
data=pd.read_csv('Social Media DataSet.csv')

In [3]:
df=pd.DataFrame(data)

In [4]:
df

,participant_id,age,gender,occupation,region,most_used_platform,platforms_used_count,daily_screen_hours,daily_notifications,night_time_use,...,life_satisfaction_1to10,loneliness_1to10,self_esteem_1to10,fomo_1to10,social_comparison_1to10,physical_activity_days_per_week,uses_screen_time_limits,attempted_digital_detox,seeks_mental_health_support,wellbeing_band
0,P300000,33,Male,Student,Latin America,TikTok,8,3.2,172,Never,...,9,6,4,6,8,4,No,No,No,At-risk
1,P300001,23,Female,Full-time employed,Oceania,Instagram,8,4.5,38,Often,...,7,5,8,5,8,4,No,"Yes, failed",Yes,At-risk
2,P300002,56,Female,Full-time employed,Africa,Instagram,1,5.3,74,Every night,...,8,7,3,2,3,5,No,No,No,Moderate
3,P300003,13,Male,Student,Europe,YouTube,4,3.4,49,Sometimes,...,10,6,6,1,5,4,No,"Yes, failed",Yes,Moderate
4,P300004,36,Female,Student,Asia,LinkedIn,5,5.8,227,Never,...,4,6,8,7,9,3,Yes,"Yes, succeeded",No,Moderate
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6995,P306995,30,Male,Part-time employed,Europe,Snapchat,4,3.6,74,Never,...,4,4,6,3,10,2,Yes,No,No,Good
6996,P306996,28,Male,Self-employed,North America,Facebook,3,5.0,104,Every night,...,8,1,7,6,7,1,No,"Yes, failed",No,Moderate
6997,P306997,26,Prefer not to say,Unemployed,Oceania,LinkedIn,3,1.2,25,Never,...,9,4,5,1,6,3,No,No,No,Good
6998,P306998,22,Female,Student,Europe,Snapchat,4,3.6,182,Sometimes,...,5,7,4,1,6,2,No,"Yes, failed",No,Good
6999,P306999,29,Male,Student,Asia,Facebook,1,5.8,14,Every night,...,5,7,4,9,6,3,No,No,Considering it,Moderate

In [10]:
clm=df.select_dtypes(include=['object','string']).columns 
df[clm]=df[clm].apply(lambda x:(
    x.str.strip().str.replace('"',"",regex=False).str.replace("'","",regex=False).str.replace('-',"",regex=False).str.replace('-',"",regex=False).str.title()
))

In [40]:
df

,participant_id,age,gender,occupation,region,most_used_platform,platforms_used_count,daily_screen_hours,daily_notifications,night_time_use,...,life_satisfaction_1to10,loneliness_1to10,self_esteem_1to10,fomo_1to10,social_comparison_1to10,physical_activity_days_per_week,uses_screen_time_limits,attempted_digital_detox,seeks_mental_health_support,wellbeing_band
0,P300002,56.0,Female,Fulltime Employed,Africa,Instagram,1,5.3,74,Every Night,...,8,7,3,2,3,5,No,No,No,Moderate
1,P300005,28.0,Female,Fulltime Employed,Latin America,Youtube,5,3.6,29,Every Night,...,7,9,5,4,3,3,No,No,Yes,Good
2,P300011,46.0,Female,Unemployed,Asia,Youtube,1,0.2,5,Often,...,9,3,10,1,3,4,No,No,No,Good
3,P300012,30.0,Female,Fulltime Employed,Asia,Tiktok,4,4.2,50,Every Night,...,5,6,5,6,7,2,Yes,No,No,Moderate
4,P300017,23.0,Male,Student,Europe,Tiktok,6,3.6,154,Often,...,8,6,6,5,3,3,No,No,Considering It,Moderate
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3049,P306988,33.0,Female,Student,Europe,Tiktok,5,2.6,69,Sometimes,...,8,6,4,4,5,4,Yes,No,No,Good
3050,P306989,22.0,Male,Student,Latin America,Youtube,4,7.4,74,Sometimes,...,7,7,7,9,9,2,No,No,No,Moderate
3051,P306990,14.0,Female,Fulltime Employed,Latin America,Youtube,2,2.5,57,Sometimes,...,9,4,6,2,8,3,No,No,Yes,Good
3052,P306995,30.0,Male,Parttime Employed,Europe,Snapchat,4,3.6,74,Never,...,4,4,6,3,10,2,Yes,No,No,Good
3053,P306999,29.0,Male,Student,Asia,Facebook,1,5.8,14,Every Night,...,5,7,4,9,6,3,No,No,Considering It,Moderate

In [10]:
df.isna().sum()

participant_id                           0
age                                      0
gender                                  70
occupation                               0
region                                   0
most_used_platform                       0
platforms_used_count                     0
daily_screen_hours                       0
daily_notifications                      0
night_time_use                           0
minutes_to_first_check_after_waking      0
primary_purpose                          0
avg_sleep_hours                        105
anxiety_score_0to27                      0
low_mood_score_0to27                     0
life_satisfaction_1to10                  0
loneliness_1to10                         0
self_esteem_1to10                        0
fomo_1to10                               0
social_comparison_1to10                  0
physical_activity_days_per_week          0
uses_screen_time_limits                  0
attempted_digital_detox                  0
seeks_mental_health_support              0
wellbeing_band                           0
dtype: int64

In [12]:
df['participant_id']=df['participant_id'].where(df['participant_id'].astype(str).str.fullmatch(r"^[A-Za-z]+([0-9]+)$"),np.nan)

In [13]:
df['age']=df['age'].where(df['age']>0,np.nan)

In [14]:
df.loc[0,'age']=-33

In [15]:
df[df.age<=0]

,participant_id,age,gender,occupation,region,most_used_platform,platforms_used_count,daily_screen_hours,daily_notifications,night_time_use,...,life_satisfaction_1to10,loneliness_1to10,self_esteem_1to10,fomo_1to10,social_comparison_1to10,physical_activity_days_per_week,uses_screen_time_limits,attempted_digital_detox,seeks_mental_health_support,wellbeing_band
0,P300000,-33,Male,Student,Latin America,Tiktok,8,3.2,172,Never,...,9,6,4,6,8,4,No,No,No,Atrisk

In [16]:
df['age']=df['age'].where(df['age']>0,np.nan)

In [17]:
df

,participant_id,age,gender,occupation,region,most_used_platform,platforms_used_count,daily_screen_hours,daily_notifications,night_time_use,...,life_satisfaction_1to10,loneliness_1to10,self_esteem_1to10,fomo_1to10,social_comparison_1to10,physical_activity_days_per_week,uses_screen_time_limits,attempted_digital_detox,seeks_mental_health_support,wellbeing_band
0,P300000,NaN,Male,Student,Latin America,Tiktok,8,3.2,172,Never,...,9,6,4,6,8,4,No,No,No,Atrisk
1,P300001,23.0,Female,Fulltime Employed,Oceania,Instagram,8,4.5,38,Often,...,7,5,8,5,8,4,No,"Yes, Failed",Yes,Atrisk
2,P300002,56.0,Female,Fulltime Employed,Africa,Instagram,1,5.3,74,Every Night,...,8,7,3,2,3,5,No,No,No,Moderate
3,P300003,13.0,Male,Student,Europe,Youtube,4,3.4,49,Sometimes,...,10,6,6,1,5,4,No,"Yes, Failed",Yes,Moderate
4,P300004,36.0,Female,Student,Asia,Linkedin,5,5.8,227,Never,...,4,6,8,7,9,3,Yes,"Yes, Succeeded",No,Moderate
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6995,P306995,30.0,Male,Parttime Employed,Europe,Snapchat,4,3.6,74,Never,...,4,4,6,3,10,2,Yes,No,No,Good
6996,P306996,28.0,Male,Selfemployed,North America,Facebook,3,5.0,104,Every Night,...,8,1,7,6,7,1,No,"Yes, Failed",No,Moderate
6997,P306997,26.0,Prefer Not To Say,Unemployed,Oceania,Linkedin,3,1.2,25,Never,...,9,4,5,1,6,3,No,No,No,Good
6998,P306998,22.0,Female,Student,Europe,Snapchat,4,3.6,182,Sometimes,...,5,7,4,1,6,2,No,"Yes, Failed",No,Good
6999,P306999,29.0,Male,Student,Asia,Facebook,1,5.8,14,Every Night,...,5,7,4,9,6,3,No,No,Considering It,Moderate

In [18]:
df.groupby('gender').count()

,participant_id,age,occupation,region,most_used_platform,platforms_used_count,daily_screen_hours,daily_notifications,night_time_use,minutes_to_first_check_after_waking,...,life_satisfaction_1to10,loneliness_1to10,self_esteem_1to10,fomo_1to10,social_comparison_1to10,physical_activity_days_per_week,uses_screen_time_limits,attempted_digital_detox,seeks_mental_health_support,wellbeing_band
gender,,,,,,,,,,,,,,,,,,,,,
Female,3240,3240,3240,3240,3240,3240,3240,3240,3240,3240,...,3240,3240,3240,3240,3240,3240,3240,3240,3240,3240
Male,3261,3260,3261,3261,3261,3261,3261,3261,3261,3261,...,3261,3261,3261,3261,3261,3261,3261,3261,3261,3261
Nonbinary,276,276,276,276,276,276,276,276,276,276,...,276,276,276,276,276,276,276,276,276,276
Prefer Not To Say,153,153,153,153,153,153,153,153,153,153,...,153,153,153,153,153,153,153,153,153,153

In [19]:
dat=['Female','Male','Nonbinary']
df['gender']=df['gender'].where(df['gender'].isin(dat),np.nan)

In [20]:
df.groupby('gender').count()

,participant_id,age,occupation,region,most_used_platform,platforms_used_count,daily_screen_hours,daily_notifications,night_time_use,minutes_to_first_check_after_waking,...,life_satisfaction_1to10,loneliness_1to10,self_esteem_1to10,fomo_1to10,social_comparison_1to10,physical_activity_days_per_week,uses_screen_time_limits,attempted_digital_detox,seeks_mental_health_support,wellbeing_band
gender,,,,,,,,,,,,,,,,,,,,,
Female,3240,3240,3240,3240,3240,3240,3240,3240,3240,3240,...,3240,3240,3240,3240,3240,3240,3240,3240,3240,3240
Male,3261,3260,3261,3261,3261,3261,3261,3261,3261,3261,...,3261,3261,3261,3261,3261,3261,3261,3261,3261,3261
Nonbinary,276,276,276,276,276,276,276,276,276,276,...,276,276,276,276,276,276,276,276,276,276

In [21]:
df.groupby('gender').count()

,participant_id,age,occupation,region,most_used_platform,platforms_used_count,daily_screen_hours,daily_notifications,night_time_use,minutes_to_first_check_after_waking,...,life_satisfaction_1to10,loneliness_1to10,self_esteem_1to10,fomo_1to10,social_comparison_1to10,physical_activity_days_per_week,uses_screen_time_limits,attempted_digital_detox,seeks_mental_health_support,wellbeing_band
gender,,,,,,,,,,,,,,,,,,,,,
Female,3240,3240,3240,3240,3240,3240,3240,3240,3240,3240,...,3240,3240,3240,3240,3240,3240,3240,3240,3240,3240
Male,3261,3260,3261,3261,3261,3261,3261,3261,3261,3261,...,3261,3261,3261,3261,3261,3261,3261,3261,3261,3261
Nonbinary,276,276,276,276,276,276,276,276,276,276,...,276,276,276,276,276,276,276,276,276,276

In [22]:
df

,participant_id,age,gender,occupation,region,most_used_platform,platforms_used_count,daily_screen_hours,daily_notifications,night_time_use,...,life_satisfaction_1to10,loneliness_1to10,self_esteem_1to10,fomo_1to10,social_comparison_1to10,physical_activity_days_per_week,uses_screen_time_limits,attempted_digital_detox,seeks_mental_health_support,wellbeing_band
0,P300000,NaN,Male,Student,Latin America,Tiktok,8,3.2,172,Never,...,9,6,4,6,8,4,No,No,No,Atrisk
1,P300001,23.0,Female,Fulltime Employed,Oceania,Instagram,8,4.5,38,Often,...,7,5,8,5,8,4,No,"Yes, Failed",Yes,Atrisk
2,P300002,56.0,Female,Fulltime Employed,Africa,Instagram,1,5.3,74,Every Night,...,8,7,3,2,3,5,No,No,No,Moderate
3,P300003,13.0,Male,Student,Europe,Youtube,4,3.4,49,Sometimes,...,10,6,6,1,5,4,No,"Yes, Failed",Yes,Moderate
4,P300004,36.0,Female,Student,Asia,Linkedin,5,5.8,227,Never,...,4,6,8,7,9,3,Yes,"Yes, Succeeded",No,Moderate
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6995,P306995,30.0,Male,Parttime Employed,Europe,Snapchat,4,3.6,74,Never,...,4,4,6,3,10,2,Yes,No,No,Good
6996,P306996,28.0,Male,Selfemployed,North America,Facebook,3,5.0,104,Every Night,...,8,1,7,6,7,1,No,"Yes, Failed",No,Moderate
6997,P306997,26.0,NaN,Unemployed,Oceania,Linkedin,3,1.2,25,Never,...,9,4,5,1,6,3,No,No,No,Good
6998,P306998,22.0,Female,Student,Europe,Snapchat,4,3.6,182,Sometimes,...,5,7,4,1,6,2,No,"Yes, Failed",No,Good
6999,P306999,29.0,Male,Student,Asia,Facebook,1,5.8,14,Every Night,...,5,7,4,9,6,3,No,No,Considering It,Moderate

In [23]:
df.dropna(inplace=True,ignore_index=True)

In [24]:
df

,participant_id,age,gender,occupation,region,most_used_platform,platforms_used_count,daily_screen_hours,daily_notifications,night_time_use,...,life_satisfaction_1to10,loneliness_1to10,self_esteem_1to10,fomo_1to10,social_comparison_1to10,physical_activity_days_per_week,uses_screen_time_limits,attempted_digital_detox,seeks_mental_health_support,wellbeing_band
0,P300001,23.0,Female,Fulltime Employed,Oceania,Instagram,8,4.5,38,Often,...,7,5,8,5,8,4,No,"Yes, Failed",Yes,Atrisk
1,P300002,56.0,Female,Fulltime Employed,Africa,Instagram,1,5.3,74,Every Night,...,8,7,3,2,3,5,No,No,No,Moderate
2,P300003,13.0,Male,Student,Europe,Youtube,4,3.4,49,Sometimes,...,10,6,6,1,5,4,No,"Yes, Failed",Yes,Moderate
3,P300004,36.0,Female,Student,Asia,Linkedin,5,5.8,227,Never,...,4,6,8,7,9,3,Yes,"Yes, Succeeded",No,Moderate
4,P300005,28.0,Female,Fulltime Employed,Latin America,Youtube,5,3.6,29,Every Night,...,7,9,5,4,3,3,No,No,Yes,Good
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6671,P306994,24.0,Female,Parttime Employed,Latin America,Tiktok,6,5.2,120,Never,...,9,2,6,5,7,3,No,"Yes, Failed",No,Atrisk
6672,P306995,30.0,Male,Parttime Employed,Europe,Snapchat,4,3.6,74,Never,...,4,4,6,3,10,2,Yes,No,No,Good
6673,P306996,28.0,Male,Selfemployed,North America,Facebook,3,5.0,104,Every Night,...,8,1,7,6,7,1,No,"Yes, Failed",No,Moderate
6674,P306998,22.0,Female,Student,Europe,Snapchat,4,3.6,182,Sometimes,...,5,7,4,1,6,2,No,"Yes, Failed",No,Good
6675,P306999,29.0,Male,Student,Asia,Facebook,1,5.8,14,Every Night,...,5,7,4,9,6,3,No,No,Considering It,Moderate

In [25]:
df['region']=df['region'].where(df['region'].astype(str).str.fullmatch(r'^[A-Za-z]+(\s+[A-Za-z]+)?$'),np.nan)

In [26]:
df.dropna(inplace=True,ignore_index=True)

In [27]:
df

,participant_id,age,gender,occupation,region,most_used_platform,platforms_used_count,daily_screen_hours,daily_notifications,night_time_use,...,life_satisfaction_1to10,loneliness_1to10,self_esteem_1to10,fomo_1to10,social_comparison_1to10,physical_activity_days_per_week,uses_screen_time_limits,attempted_digital_detox,seeks_mental_health_support,wellbeing_band
0,P300001,23.0,Female,Fulltime Employed,Oceania,Instagram,8,4.5,38,Often,...,7,5,8,5,8,4,No,"Yes, Failed",Yes,Atrisk
1,P300002,56.0,Female,Fulltime Employed,Africa,Instagram,1,5.3,74,Every Night,...,8,7,3,2,3,5,No,No,No,Moderate
2,P300003,13.0,Male,Student,Europe,Youtube,4,3.4,49,Sometimes,...,10,6,6,1,5,4,No,"Yes, Failed",Yes,Moderate
3,P300004,36.0,Female,Student,Asia,Linkedin,5,5.8,227,Never,...,4,6,8,7,9,3,Yes,"Yes, Succeeded",No,Moderate
4,P300005,28.0,Female,Fulltime Employed,Latin America,Youtube,5,3.6,29,Every Night,...,7,9,5,4,3,3,No,No,Yes,Good
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6671,P306994,24.0,Female,Parttime Employed,Latin America,Tiktok,6,5.2,120,Never,...,9,2,6,5,7,3,No,"Yes, Failed",No,Atrisk
6672,P306995,30.0,Male,Parttime Employed,Europe,Snapchat,4,3.6,74,Never,...,4,4,6,3,10,2,Yes,No,No,Good
6673,P306996,28.0,Male,Selfemployed,North America,Facebook,3,5.0,104,Every Night,...,8,1,7,6,7,1,No,"Yes, Failed",No,Moderate
6674,P306998,22.0,Female,Student,Europe,Snapchat,4,3.6,182,Sometimes,...,5,7,4,1,6,2,No,"Yes, Failed",No,Good
6675,P306999,29.0,Male,Student,Asia,Facebook,1,5.8,14,Every Night,...,5,7,4,9,6,3,No,No,Considering It,Moderate

In [28]:
df['most_used_platform']=df['most_used_platform'].where(df['most_used_platform'].astype(str).str.fullmatch(r'^[A-Za-z]+(\s+[A-Za-z]+)?$'),np.nan)

In [33]:
df['wellbeing_band']=df['wellbeing_band'].where(df['wellbeing_band'].astype(str).str.fullmatch(r'^[A-Za-z]+(\s+[A-Za-z]+)?$'),np.nan)

In [34]:
df.isnull().sum()

participant_id                            0
age                                       0
gender                                    0
occupation                                0
region                                    0
most_used_platform                      559
platforms_used_count                      0
daily_screen_hours                        0
daily_notifications                       0
night_time_use                            0
minutes_to_first_check_after_waking       0
primary_purpose                           0
avg_sleep_hours                           0
anxiety_score_0to27                       0
low_mood_score_0to27                      0
life_satisfaction_1to10                   0
loneliness_1to10                          0
self_esteem_1to10                         0
fomo_1to10                                0
social_comparison_1to10                   0
physical_activity_days_per_week           0
uses_screen_time_limits                   0
attempted_digital_detox                3332
seeks_mental_health_support               0
wellbeing_band                            0
dtype: int64

In [35]:
df.groupby('most_used_platform').count()

,participant_id,age,gender,occupation,region,platforms_used_count,daily_screen_hours,daily_notifications,night_time_use,minutes_to_first_check_after_waking,...,life_satisfaction_1to10,loneliness_1to10,self_esteem_1to10,fomo_1to10,social_comparison_1to10,physical_activity_days_per_week,uses_screen_time_limits,attempted_digital_detox,seeks_mental_health_support,wellbeing_band
most_used_platform,,,,,,,,,,,,,,,,,,,,,
Facebook,498,498,498,498,498,498,498,498,498,498,...,498,498,498,498,498,498,498,223,498,498
Instagram,1625,1625,1625,1625,1625,1625,1625,1625,1625,1625,...,1625,1625,1625,1625,1625,1625,1625,827,1625,1625
Linkedin,258,258,258,258,258,258,258,258,258,258,...,258,258,258,258,258,258,258,136,258,258
Reddit,392,392,392,392,392,392,392,392,392,392,...,392,392,392,392,392,392,392,179,392,392
Snapchat,477,477,477,477,477,477,477,477,477,477,...,477,477,477,477,477,477,477,249,477,477
Tiktok,1650,1650,1650,1650,1650,1650,1650,1650,1650,1650,...,1650,1650,1650,1650,1650,1650,1650,824,1650,1650
Youtube,1217,1217,1217,1217,1217,1217,1217,1217,1217,1217,...,1217,1217,1217,1217,1217,1217,1217,616,1217,1217

In [51]:
df.duplicated(keep='first')

0       False
1       False
2       False
3       False
4       False
        ...
3049    False
3050    False
3051    False
3052    False
3053    False
Length: 3054, dtype: bool

In [37]:
df.tail(50)

,participant_id,age,gender,occupation,region,most_used_platform,platforms_used_count,daily_screen_hours,daily_notifications,night_time_use,...,life_satisfaction_1to10,loneliness_1to10,self_esteem_1to10,fomo_1to10,social_comparison_1to10,physical_activity_days_per_week,uses_screen_time_limits,attempted_digital_detox,seeks_mental_health_support,wellbeing_band
6626,P306949,13.0,Male,Student,Asia,Youtube,3,2.8,43,Sometimes,...,6,2,6,6,6,3,Yes,NaN,No,Good
6627,P306950,18.0,Male,Fulltime Employed,Asia,Tiktok,3,0.9,10,Sometimes,...,7,4,9,3,4,2,Yes,NaN,No,Moderate
6628,P306951,22.0,Female,Student,North America,NaN,3,3.2,49,Often,...,5,5,8,5,5,4,Yes,No,Considering It,Moderate
6629,P306952,44.0,Male,Student,Latin America,Tiktok,6,4.5,36,Never,...,5,6,6,8,7,4,No,No,No,Moderate
6630,P306953,26.0,Female,Student,North America,Youtube,1,6.3,196,Sometimes,...,7,7,2,8,7,2,Yes,NaN,No,Atrisk
6631,P306954,43.0,Female,Fulltime Employed,Europe,Tiktok,3,10.3,239,Sometimes,...,7,6,7,5,6,7,Yes,NaN,No,Atrisk
6632,P306955,30.0,Male,Student,Africa,Youtube,3,1.2,27,Never,...,7,6,7,8,3,3,Yes,No,No,Good
6633,P306956,23.0,Female,Student,North America,NaN,4,2.0,58,Never,...,6,3,6,5,4,2,Yes,NaN,No,Moderate
6634,P306957,28.0,Female,Student,Europe,Instagram,3,2.4,40,Every Night,...,5,1,5,1,7,5,No,NaN,Considering It,Moderate
6635,P306958,37.0,Female,Fulltime Employed,North America,Tiktok,5,9.5,371,Often,...,4,9,4,7,6,4,Yes,No,Considering It,Atrisk
6636,P306959,28.0,Male,Selfemployed,Africa,NaN,2,5.4,148,Every Night,...,8,6,9,5,5,2,No,NaN,No,Moderate
6637,P306960,24.0,Female,Student,Latin America,Youtube,2,1.7,98,Sometimes,...,9,5,7,3,3,2,Yes,NaN,Yes,Good
6638,P306961,21.0,Female,Fulltime Employed,Asia,Tiktok,1,2.0,34,Sometimes,...,8,5,5,8,1,5,No,NaN,Yes,Good
6639,P306962,44.0,Female,Retired,Africa,Youtube,5,0.5,8,Every Night,...,5,3,5,7,8,3,No,NaN,Considering It,Atrisk
6640,P306963,14.0,Male,Fulltime Employed,Latin America,Tiktok,2,6.9,115,Often,...,5,4,4,5,8,2,Yes,No,No,Atrisk
6641,P306964,28.0,Female,Retired,North America,Youtube,4,2.0,57,Sometimes,...,9,3,10,4,5,2,Yes,NaN,No,Good
6642,P306965,15.0,Male,Student,Europe,Reddit,3,3.1,41,Sometimes,...,7,4,8,2,4,2,No,No,No,Moderate
6643,P306966,37.0,Female,Student,Europe,Facebook,5,2.8,50,Sometimes,...,7,6,5,4,6,4,No,NaN,Considering It,Good
6644,P306967,13.0,Male,Selfemployed,Europe,Tiktok,3,2.4,40,Every Night,...,6,6,8,3,9,3,No,NaN,Considering It,Moderate
6645,P306968,36.0,Female,Selfemployed,North America,Tiktok,3,7.2,84,Sometimes,...,5,6,4,5,9,2,No,No,No,Moderate
6646,P306969,50.0,Female,Parttime Employed,Asia,Instagram,3,1.3,24,Never,...,7,1,6,3,5,0,No,No,Yes,Good
6647,P306970,26.0,Female,Parttime Employed,Oceania,Linkedin,7,2.2,62,Every Night,...,8,6,10,5,5,1,No,No,No,Moderate
6648,P306971,27.0,Male,Parttime Employed,Asia,Youtube,1,1.5,7,Sometimes,...,8,6,3,6,6,3,No,No,No,Moderate
6649,P306972,37.0,Male,Fulltime Employed,Europe,Instagram,3,3.8,64,Sometimes,...,8,6,7,4,6,3,Yes,No,Yes,Moderate
6650,P306973,13.0,Male,Fulltime Employed,Europe,Snapchat,1,4.9,57,Never,...,6,5,5,4,9,3,Yes,No,Considering It,Moderate
6651,P306974,17.0,Male,Student,Europe,Youtube,3,4.5,140,Often,...,8,7,7,1,7,3,Yes,NaN,No,Good
6652,P306975,32.0,Male,Unemployed,Europe,Snapchat,3,4.2,80,Every Night,...,6,5,6,8,5,5,Yes,No,No,Atrisk
6653,P306976,21.0,Male,Student,Asia,Tiktok,3,1.6,7,Sometimes,...,9,1,7,3,6,6,No,NaN,Yes,Good
6654,P306977,30.0,Female,Fulltime Employed,Europe,Facebook,2,1.7,46,Often,...,7,5,7,1,3,4,No,NaN,No,Good
6655,P306978,19.0,Male,Parttime Employed,North America,Reddit,2,5.5,160,Sometimes,...,6,7,10,4,7,4,No,NaN,No,Good
6656,P306979,31.0,Male,Fulltime Employed,Europe,Instagram,2,5.5,114,Every Night,...,6,6,5,9,6,3,Yes,No,Considering It,Moderate
6657,P306980,21.0,Male,Unemployed,Europe,Tiktok,4,2.2,85,Sometimes,...,9,3,6,4,4,2,Yes,NaN,No,Atrisk
6658,P306981,27.0,Nonbinary,Fulltime Employed,Latin America,Instagram,3,2.1,60,Sometimes,...,7,8,8,7,7,3,Yes,NaN,No,Good
6659,P306982,21.0,Male,Student,Europe,NaN,5,8.5,46,Sometimes,...,8,4,6,7,8,4,Yes,No,Considering It,Atrisk
6660,P306983,20.0,Male,Unemployed,Europe,Reddit,2,1.1,11,Every Night,...,6,6,7,1,2,2,No,NaN,Yes,Good
6661,P306984,21.0,Female,Student,Europe,Instagram,2,1.9,25,Every Night,...,6,10,4,7,1,3,No,NaN,Yes,Moderate
6662,P306985,28.0,Nonbinary,Parttime Employed,Asia,Youtube,7,1.2,7,Sometimes,...,5,5,5,1,8,2,No,NaN,No,Good
6663,P306986,30.0,Female,Student,Asia,Youtube,4,3.4,34,Sometimes,...,8,1,6,6,3,3,No,NaN,No,Moderate
6664,P306987,36.0,Male,Parttime Employed,Europe,Reddit,3,2.2,47,Never,...,8,3,9,2,3,2,No,NaN,No,Moderate
6665,P306988,33.0,Female,Student,Europe,Tiktok,5,2.6,69,Sometimes,...,8,6,4,4,5,4,Yes,No,No,Good
6666,P306989,22.0,Male,Student,Latin America,Youtube,4,7.4,74,Sometimes,...,7,7,7,9,9,2,No,No,No,Moderate
6667,P306990,14.0,Female,Fulltime Employed,Latin America,Youtube,2,2.5,57,Sometimes,...,9,4,6,2,8,3,No,No,Yes,Good
6668,P306991,38.0,Male,Student,Europe,Reddit,4,1.5,42,Every Night,...,7,5,6,3,5,5,Yes,NaN,No,Good
6669,P306992,36.0,Male,Fulltime Employed,Asia,Instagram,1,2.9,119,Often,...,8,4,8,2,4,2,Yes,NaN,No,Good
6670,P306993,13.0,Male,Selfemployed,North America,NaN,3,9.6,180,Sometimes,...,5,10,7,6,8,2,Yes,NaN,Yes,Atrisk
6671,P306994,24.0,Female,Parttime Employed,Latin America,Tiktok,6,5.2,120,Never,...,9,2,6,5,7,3,No,NaN,No,Atrisk
6672,P306995,30.0,Male,Parttime Employed,Europe,Snapchat,4,3.6,74,Never,...,4,4,6,3,10,2,Yes,No,No,Good
6673,P306996,28.0,Male,Selfemployed,North America,Facebook,3,5.0,104,Every Night,...,8,1,7,6,7,1,No,NaN,No,Moderate
6674,P306998,22.0,Female,Student,Europe,Snapchat,4,3.6,182,Sometimes,...,5,7,4,1,6,2,No,NaN,No,Good
6675,P306999,29.0,Male,Student,Asia,Facebook,1,5.8,14,Every Night,...,5,7,4,9,6,3,No,No,Considering It,Moderate

In [38]:
df.dropna(inplace=True,ignore_index=True)

In [39]:
df

,participant_id,age,gender,occupation,region,most_used_platform,platforms_used_count,daily_screen_hours,daily_notifications,night_time_use,...,life_satisfaction_1to10,loneliness_1to10,self_esteem_1to10,fomo_1to10,social_comparison_1to10,physical_activity_days_per_week,uses_screen_time_limits,attempted_digital_detox,seeks_mental_health_support,wellbeing_band
0,P300002,56.0,Female,Fulltime Employed,Africa,Instagram,1,5.3,74,Every Night,...,8,7,3,2,3,5,No,No,No,Moderate
1,P300005,28.0,Female,Fulltime Employed,Latin America,Youtube,5,3.6,29,Every Night,...,7,9,5,4,3,3,No,No,Yes,Good
2,P300011,46.0,Female,Unemployed,Asia,Youtube,1,0.2,5,Often,...,9,3,10,1,3,4,No,No,No,Good
3,P300012,30.0,Female,Fulltime Employed,Asia,Tiktok,4,4.2,50,Every Night,...,5,6,5,6,7,2,Yes,No,No,Moderate
4,P300017,23.0,Male,Student,Europe,Tiktok,6,3.6,154,Often,...,8,6,6,5,3,3,No,No,Considering It,Moderate
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3049,P306988,33.0,Female,Student,Europe,Tiktok,5,2.6,69,Sometimes,...,8,6,4,4,5,4,Yes,No,No,Good
3050,P306989,22.0,Male,Student,Latin America,Youtube,4,7.4,74,Sometimes,...,7,7,7,9,9,2,No,No,No,Moderate
3051,P306990,14.0,Female,Fulltime Employed,Latin America,Youtube,2,2.5,57,Sometimes,...,9,4,6,2,8,3,No,No,Yes,Good
3052,P306995,30.0,Male,Parttime Employed,Europe,Snapchat,4,3.6,74,Never,...,4,4,6,3,10,2,Yes,No,No,Good
3053,P306999,29.0,Male,Student,Asia,Facebook,1,5.8,14,Every Night,...,5,7,4,9,6,3,No,No,Considering It,Moderate

In [41]:
df.drop('attempted_digital_detox',axis=1)

,participant_id,age,gender,occupation,region,most_used_platform,platforms_used_count,daily_screen_hours,daily_notifications,night_time_use,...,low_mood_score_0to27,life_satisfaction_1to10,loneliness_1to10,self_esteem_1to10,fomo_1to10,social_comparison_1to10,physical_activity_days_per_week,uses_screen_time_limits,seeks_mental_health_support,wellbeing_band
0,P300002,56.0,Female,Fulltime Employed,Africa,Instagram,1,5.3,74,Every Night,...,6,8,7,3,2,3,5,No,No,Moderate
1,P300005,28.0,Female,Fulltime Employed,Latin America,Youtube,5,3.6,29,Every Night,...,4,7,9,5,4,3,3,No,Yes,Good
2,P300011,46.0,Female,Unemployed,Asia,Youtube,1,0.2,5,Often,...,7,9,3,10,1,3,4,No,No,Good
3,P300012,30.0,Female,Fulltime Employed,Asia,Tiktok,4,4.2,50,Every Night,...,0,5,6,5,6,7,2,Yes,No,Moderate
4,P300017,23.0,Male,Student,Europe,Tiktok,6,3.6,154,Often,...,3,8,6,6,5,3,3,No,Considering It,Moderate
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3049,P306988,33.0,Female,Student,Europe,Tiktok,5,2.6,69,Sometimes,...,8,8,6,4,4,5,4,Yes,No,Good
3050,P306989,22.0,Male,Student,Latin America,Youtube,4,7.4,74,Sometimes,...,1,7,7,7,9,9,2,No,No,Moderate
3051,P306990,14.0,Female,Fulltime Employed,Latin America,Youtube,2,2.5,57,Sometimes,...,9,9,4,6,2,8,3,No,Yes,Good
3052,P306995,30.0,Male,Parttime Employed,Europe,Snapchat,4,3.6,74,Never,...,8,4,4,6,3,10,2,Yes,No,Good
3053,P306999,29.0,Male,Student,Asia,Facebook,1,5.8,14,Every Night,...,8,5,7,4,9,6,3,No,Considering It,Moderate

In [42]:
df.groupby('wellbeing_band').count()

,participant_id,age,gender,occupation,region,most_used_platform,platforms_used_count,daily_screen_hours,daily_notifications,night_time_use,...,low_mood_score_0to27,life_satisfaction_1to10,loneliness_1to10,self_esteem_1to10,fomo_1to10,social_comparison_1to10,physical_activity_days_per_week,uses_screen_time_limits,attempted_digital_detox,wellbeing_band
seeks_mental_health_support,,,,,,,,,,,,,,,,,,,,,
Considering It,644,644,644,644,644,644,644,644,644,644,...,644,644,644,644,644,644,644,644,644,644
No,1843,1843,1843,1843,1843,1843,1843,1843,1843,1843,...,1843,1843,1843,1843,1843,1843,1843,1843,1843,1843
Yes,567,567,567,567,567,567,567,567,567,567,...,567,567,567,567,567,567,567,567,567,567

In [43]:
df.groupby('wellbeing_band').count()

,participant_id,age,gender,occupation,region,most_used_platform,platforms_used_count,daily_screen_hours,daily_notifications,night_time_use,...,low_mood_score_0to27,life_satisfaction_1to10,loneliness_1to10,self_esteem_1to10,fomo_1to10,social_comparison_1to10,physical_activity_days_per_week,uses_screen_time_limits,attempted_digital_detox,seeks_mental_health_support
wellbeing_band,,,,,,,,,,,,,,,,,,,,,
Atrisk,424,424,424,424,424,424,424,424,424,424,...,424,424,424,424,424,424,424,424,424,424
Good,971,971,971,971,971,971,971,971,971,971,...,971,971,971,971,971,971,971,971,971,971
Moderate,1659,1659,1659,1659,1659,1659,1659,1659,1659,1659,...,1659,1659,1659,1659,1659,1659,1659,1659,1659,1659

In [44]:
df

,participant_id,age,gender,occupation,region,most_used_platform,platforms_used_count,daily_screen_hours,daily_notifications,night_time_use,...,life_satisfaction_1to10,loneliness_1to10,self_esteem_1to10,fomo_1to10,social_comparison_1to10,physical_activity_days_per_week,uses_screen_time_limits,attempted_digital_detox,seeks_mental_health_support,wellbeing_band
0,P300002,56.0,Female,Fulltime Employed,Africa,Instagram,1,5.3,74,Every Night,...,8,7,3,2,3,5,No,No,No,Moderate
1,P300005,28.0,Female,Fulltime Employed,Latin America,Youtube,5,3.6,29,Every Night,...,7,9,5,4,3,3,No,No,Yes,Good
2,P300011,46.0,Female,Unemployed,Asia,Youtube,1,0.2,5,Often,...,9,3,10,1,3,4,No,No,No,Good
3,P300012,30.0,Female,Fulltime Employed,Asia,Tiktok,4,4.2,50,Every Night,...,5,6,5,6,7,2,Yes,No,No,Moderate
4,P300017,23.0,Male,Student,Europe,Tiktok,6,3.6,154,Often,...,8,6,6,5,3,3,No,No,Considering It,Moderate
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3049,P306988,33.0,Female,Student,Europe,Tiktok,5,2.6,69,Sometimes,...,8,6,4,4,5,4,Yes,No,No,Good
3050,P306989,22.0,Male,Student,Latin America,Youtube,4,7.4,74,Sometimes,...,7,7,7,9,9,2,No,No,No,Moderate
3051,P306990,14.0,Female,Fulltime Employed,Latin America,Youtube,2,2.5,57,Sometimes,...,9,4,6,2,8,3,No,No,Yes,Good
3052,P306995,30.0,Male,Parttime Employed,Europe,Snapchat,4,3.6,74,Never,...,4,4,6,3,10,2,Yes,No,No,Good
3053,P306999,29.0,Male,Student,Asia,Facebook,1,5.8,14,Every Night,...,5,7,4,9,6,3,No,No,Considering It,Moderate

In [46]:
df.drop('attempted_digital_detox',axis=1,inplace=True)

In [47]:
df

,participant_id,age,gender,occupation,region,most_used_platform,platforms_used_count,daily_screen_hours,daily_notifications,night_time_use,...,low_mood_score_0to27,life_satisfaction_1to10,loneliness_1to10,self_esteem_1to10,fomo_1to10,social_comparison_1to10,physical_activity_days_per_week,uses_screen_time_limits,seeks_mental_health_support,wellbeing_band
0,P300002,56.0,Female,Fulltime Employed,Africa,Instagram,1,5.3,74,Every Night,...,6,8,7,3,2,3,5,No,No,Moderate
1,P300005,28.0,Female,Fulltime Employed,Latin America,Youtube,5,3.6,29,Every Night,...,4,7,9,5,4,3,3,No,Yes,Good
2,P300011,46.0,Female,Unemployed,Asia,Youtube,1,0.2,5,Often,...,7,9,3,10,1,3,4,No,No,Good
3,P300012,30.0,Female,Fulltime Employed,Asia,Tiktok,4,4.2,50,Every Night,...,0,5,6,5,6,7,2,Yes,No,Moderate
4,P300017,23.0,Male,Student,Europe,Tiktok,6,3.6,154,Often,...,3,8,6,6,5,3,3,No,Considering It,Moderate
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3049,P306988,33.0,Female,Student,Europe,Tiktok,5,2.6,69,Sometimes,...,8,8,6,4,4,5,4,Yes,No,Good
3050,P306989,22.0,Male,Student,Latin America,Youtube,4,7.4,74,Sometimes,...,1,7,7,7,9,9,2,No,No,Moderate
3051,P306990,14.0,Female,Fulltime Employed,Latin America,Youtube,2,2.5,57,Sometimes,...,9,9,4,6,2,8,3,No,Yes,Good
3052,P306995,30.0,Male,Parttime Employed,Europe,Snapchat,4,3.6,74,Never,...,8,4,4,6,3,10,2,Yes,No,Good
3053,P306999,29.0,Male,Student,Asia,Facebook,1,5.8,14,Every Night,...,8,5,7,4,9,6,3,No,Considering It,Moderate

In [48]:
df.reset_index(drop=True)

,participant_id,age,gender,occupation,region,most_used_platform,platforms_used_count,daily_screen_hours,daily_notifications,night_time_use,...,low_mood_score_0to27,life_satisfaction_1to10,loneliness_1to10,self_esteem_1to10,fomo_1to10,social_comparison_1to10,physical_activity_days_per_week,uses_screen_time_limits,seeks_mental_health_support,wellbeing_band
0,P300002,56.0,Female,Fulltime Employed,Africa,Instagram,1,5.3,74,Every Night,...,6,8,7,3,2,3,5,No,No,Moderate
1,P300005,28.0,Female,Fulltime Employed,Latin America,Youtube,5,3.6,29,Every Night,...,4,7,9,5,4,3,3,No,Yes,Good
2,P300011,46.0,Female,Unemployed,Asia,Youtube,1,0.2,5,Often,...,7,9,3,10,1,3,4,No,No,Good
3,P300012,30.0,Female,Fulltime Employed,Asia,Tiktok,4,4.2,50,Every Night,...,0,5,6,5,6,7,2,Yes,No,Moderate
4,P300017,23.0,Male,Student,Europe,Tiktok,6,3.6,154,Often,...,3,8,6,6,5,3,3,No,Considering It,Moderate
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3049,P306988,33.0,Female,Student,Europe,Tiktok,5,2.6,69,Sometimes,...,8,8,6,4,4,5,4,Yes,No,Good
3050,P306989,22.0,Male,Student,Latin America,Youtube,4,7.4,74,Sometimes,...,1,7,7,7,9,9,2,No,No,Moderate
3051,P306990,14.0,Female,Fulltime Employed,Latin America,Youtube,2,2.5,57,Sometimes,...,9,9,4,6,2,8,3,No,Yes,Good
3052,P306995,30.0,Male,Parttime Employed,Europe,Snapchat,4,3.6,74,Never,...,8,4,4,6,3,10,2,Yes,No,Good
3053,P306999,29.0,Male,Student,Asia,Facebook,1,5.8,14,Every Night,...,8,5,7,4,9,6,3,No,Considering It,Moderate

In [49]:
df.to_csv('Clean_Dataset.csv',index=False)